[[SZ]]
arch = "aarch64"
git-tree-sha1 = "0734961ed25848fc9e43d6c062577bfddb742dac"
os = "macos"

    [[SZ.download]]
    sha256 = "60e25113afab74b6c75a5b9b7661c27b11b1e8ec2891142bb294b7b1a8808316"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.aarch64-apple-darwin.tar.gz"
[[SZ]]
arch = "aarch64"
git-tree-sha1 = "e02fabccb81022fc2ca8163286eae285058704cc"
libc = "glibc"
os = "linux"

    [[SZ.download]]
    sha256 = "0b357f3cdde1b34a2222320da5ff8ef6ee0464c08db2790070267e14662fcf50"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.aarch64-linux-gnu.tar.gz"
[[SZ]]
arch = "aarch64"
git-tree-sha1 = "749eefb2391e99a9e4659f2b3da40b48ee0dfe7d"
libc = "musl"
os = "linux"

    [[SZ.download]]
    sha256 = "d2f40759a37eafdfd76802ebb9ab883e735c90b8db3486d993027e2930c521ff"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.aarch64-linux-musl.tar.gz"
[[SZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a931ad26348ea620e799856434c1f66d27996a7"
libc = "glibc"
os = "linux"

    [[SZ.download]]
    sha256 = "d34de090a29a80b3072ea98b156e19a9d56cfb787a727b65f383e4f237b41811"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.armv6l-linux-gnueabihf.tar.gz"
[[SZ]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "239cd00b0e3c8e6e10519b4ff34170b81775ca20"
libc = "musl"
os = "linux"

    [[SZ.download]]
    sha256 = "469b1a4b759a4a4f31fe28a7b89ddcf98bd4856a68cd6307b962817cd0698dae"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.armv6l-linux-musleabihf.tar.gz"
[[SZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0edf06ec37333ad1a52e7800998a6340678b84d5"
libc = "glibc"
os = "linux"

    [[SZ.download]]
    sha256 = "02cc01cdc8ad06a39971a0ab8d5a9f10e1903b55007287ffebdcae156f12b1d7"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.armv7l-linux-gnueabihf.tar.gz"
[[SZ]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0359ce0be05df35f3ea483dd9e018c594a0f54a8"
libc = "musl"
os = "linux"

    [[SZ.download]]
    sha256 = "2e38946585d995e912c6eac65508f7ccb96bd5dce15000ee88c782bd13f354b6"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.armv7l-linux-musleabihf.tar.gz"
[[SZ]]
arch = "i686"
git-tree-sha1 = "e84bf517d6178aa1eb5619fc8612fe407ce331d9"
libc = "glibc"
os = "linux"

    [[SZ.download]]
    sha256 = "674d2fafbb78e487352c7979b9a7b0a3a7fb7076bead1d2b9a9bf4152fa81906"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.i686-linux-gnu.tar.gz"
[[SZ]]
arch = "i686"
git-tree-sha1 = "6373be2bab37d758b20d062c2caf97e6b6749b6d"
libc = "musl"
os = "linux"

    [[SZ.download]]
    sha256 = "36a60c4b234610dda0ab931af090a0f69e1f0ea4bda1b37528a902006004f23c"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.i686-linux-musl.tar.gz"
[[SZ]]
arch = "i686"
git-tree-sha1 = "48c9070d8af4f6e584a740585b152eacdd49254f"
os = "windows"

    [[SZ.download]]
    sha256 = "5dc5f2b61d4ee8e0a4264957dc314fadc72eb7ffc592843b9b1b92e3d4af94df"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.i686-w64-mingw32.tar.gz"
[[SZ]]
arch = "powerpc64le"
git-tree-sha1 = "19392ffeec2d145fcf7ce64805581a1b44186192"
libc = "glibc"
os = "linux"

    [[SZ.download]]
    sha256 = "7d6688a074dcd3f823e2db5c5fe912229401c64cad2104cb25af23d70afb53a8"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.powerpc64le-linux-gnu.tar.gz"
[[SZ]]
arch = "x86_64"
git-tree-sha1 = "4a712ad55856931b70d12052a059aa627565163b"
os = "macos"

    [[SZ.download]]
    sha256 = "d01f5bdda856f717202721b128b9483bb069536e325fcc9aa0dc953c076a912c"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.x86_64-apple-darwin.tar.gz"
[[SZ]]
arch = "x86_64"
git-tree-sha1 = "197cee2c6e20bf4783e1a45034bae3278da6a50e"
libc = "glibc"
os = "linux"

    [[SZ.download]]
    sha256 = "87eed5fedef241658da8db8ae4a51ca66dad95a45e7b19933104517d00ac08a7"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.x86_64-linux-gnu.tar.gz"
[[SZ]]
arch = "x86_64"
git-tree-sha1 = "7f2212d6df4946c990f6ec608c10967efa9c1b5d"
libc = "musl"
os = "linux"

    [[SZ.download]]
    sha256 = "d3784b0ad3793c94c5a8f2a16a96192a59396f394cd4096759c911f8486bc387"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.x86_64-linux-musl.tar.gz"
[[SZ]]
arch = "x86_64"
git-tree-sha1 = "282068c3c5667bbc615a126b53359935e215667d"
os = "freebsd"

    [[SZ.download]]
    sha256 = "d89e88388ae042e211e832aa2501c3ebcc324be696439144b4b1a9793dcc6500"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.x86_64-unknown-freebsd.tar.gz"
[[SZ]]
arch = "x86_64"
git-tree-sha1 = "7a9870f93dd5139eca713ec6c404ff9da6a3cff5"
os = "windows"

    [[SZ.download]]
    sha256 = "5e2d2db4f52c9e473b552a4790045b7eec9187c16929eea703e6fe6c25f9f3b1"
    url = "https://github.com/JuliaBinaryWrappers/SZ_jll.jl/releases/download/SZ-v2.1.13+0/SZ.v2.1.13.x86_64-w64-mingw32.tar.gz"
