# Autogenerated wrapper script for SZ_jll for aarch64-apple-darwin
export libSZ, libhdf5sz, libnetcdfsz

using LLVMOpenMP_jll
using HDF5_jll
using NetCDF_jll
using Zlib_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("SZ")
JLLWrappers.@declare_library_product(libSZ, "@rpath/libSZ.dylib")
JLLWrappers.@declare_library_product(libhdf5sz, "@rpath/libhdf5sz.dylib")
JLLWrappers.@declare_library_product(libnetcdfsz, "@rpath/libnetcdfsz.dylib")
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll, HDF5_jll, NetCDF_jll, Zlib_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        libSZ,
        "lib/libSZ.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libhdf5sz,
        "lib/libhdf5sz.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnetcdfsz,
        "lib/libnetcdfsz.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
